version: '3.8'

services:

  main-server:
    build:
      dockerfile: Dockerfile
    image: main-server
    container_name: Training_server
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db

  main-db:
    #    health check
    image: postgres:14-alpine
    container_name: MainDB
    ports:
      - "6546:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root